services:
  backend:
    container_name: none-snmp-backend
    image: ghcr.io/nonetss/none-snmp-backend:v0.4.2
    restart: always
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@database:5432/${POSTGRES_DB:-postgres}
    depends_on:
      database:
        condition: service_healthy
    command: >
      sh -c "bunx drizzle-kit migrate --config drizzle.config.ts && bun run src/index.ts"

  frontend:
    container_name: none-snmp-frontend
    image: ghcr.io/nonetss/none-snmp-frontend:v0.4.2
    restart: always
    environment:
      - BACKEND_URL=http://backend:3000
    ports:
      - '4321:80'
    depends_on:
      - backend

  database:
    container_name: none-snmp-database
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}',
        ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
