name: Docker Image CI

on:
  push:
    branches:
      - "v*"
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Backend
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          BRANCH=${{ github.ref_name }}
          SHA=$(echo ${{ github.sha }} | cut -c1-8)
          
          IMAGE_ID=ghcr.io/$REPO_OWNER/none-snmp-backend
          IMAGE_ID=$(echo $IMAGE_ID | tr '[:upper:]' '[:lower:]')

          docker build -f backend/Dockerfile ./backend \
            -t $IMAGE_ID:latest \
            -t $IMAGE_ID:$BRANCH \
            -t $IMAGE_ID:$BRANCH-$SHA

          docker push $IMAGE_ID:latest
          docker push $IMAGE_ID:$BRANCH
          docker push $IMAGE_ID:$BRANCH-$SHA

      - name: Build and Push Frontend
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          BRANCH=${{ github.ref_name }}
          SHA=$(echo ${{ github.sha }} | cut -c1-8)
          
          IMAGE_ID=ghcr.io/$REPO_OWNER/none-snmp-frontend
          IMAGE_ID=$(echo $IMAGE_ID | tr '[:upper:]' '[:lower:]')

          docker build -f frontend/Dockerfile ./frontend \
            -t $IMAGE_ID:latest \
            -t $IMAGE_ID:$BRANCH \
            -t $IMAGE_ID:$BRANCH-$SHA

          docker push $IMAGE_ID:latest
          docker push $IMAGE_ID:$BRANCH
          docker push $IMAGE_ID:$BRANCH-$SHA

      - name: Build and Push Unified
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          BRANCH=${{ github.ref_name }}
          SHA=$(echo ${{ github.sha }} | cut -c1-8)
          
          IMAGE_ID=ghcr.io/$REPO_OWNER/none-snmp
          IMAGE_ID=$(echo $IMAGE_ID | tr '[:upper:]' '[:lower:]')

          docker build -f docker/unified/Dockerfile . \
            -t $IMAGE_ID:latest \
            -t $IMAGE_ID:$BRANCH \
            -t $IMAGE_ID:$BRANCH-$SHA

          docker push $IMAGE_ID:latest
          docker push $IMAGE_ID:$BRANCH
          docker push $IMAGE_ID:$BRANCH-$SHA
